name: Python CI

# Trigger the workflow on any push to the main branch or pull request
# his part tells GitHub to run the workflow:
#    - when there's a push to the main branch
#    - or when a pull request is made into the main branch
on:
  push:
    branches: -main
  pull_request:
    branches: -main

# This defines a job named build. A job is a set of steps that run in a GitHub-hosted virtual environment.
jobs:
  build:
    runs-on: ubuntu-latest

    # Each step is a single task that runs in the job
    steps:
      # Step 1: Check out the code from the repository
      - name: checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python Environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: pytest
